# Generated by Django 4.1.1 on 2022-11-29 08:54

from django.db import migrations, models
import recetas.models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.CharField(max_length=200, validators=[recetas.models.validate_caps]),
        ),
        migrations.AlterField(
            model_name='receta',
            name='preparación',
            field=models.TextField(max_length=5000, validators=[recetas.models.validate_caps]),
        ),
    ]
